// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type InboxEventStatus string

const (
	InboxEventStatusPending    InboxEventStatus = "pending"
	InboxEventStatusProcessed  InboxEventStatus = "processed"
	InboxEventStatusProcessing InboxEventStatus = "processing"
	InboxEventStatusFailed     InboxEventStatus = "failed"
)

func (e *InboxEventStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InboxEventStatus(s)
	case string:
		*e = InboxEventStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for InboxEventStatus: %T", src)
	}
	return nil
}

type NullInboxEventStatus struct {
	InboxEventStatus InboxEventStatus
	Valid            bool // Valid is true if InboxEventStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInboxEventStatus) Scan(value interface{}) error {
	if value == nil {
		ns.InboxEventStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InboxEventStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInboxEventStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InboxEventStatus), nil
}

type OutboxEventStatus string

const (
	OutboxEventStatusPending    OutboxEventStatus = "pending"
	OutboxEventStatusSent       OutboxEventStatus = "sent"
	OutboxEventStatusProcessing OutboxEventStatus = "processing"
	OutboxEventStatusFailed     OutboxEventStatus = "failed"
)

func (e *OutboxEventStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OutboxEventStatus(s)
	case string:
		*e = OutboxEventStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OutboxEventStatus: %T", src)
	}
	return nil
}

type NullOutboxEventStatus struct {
	OutboxEventStatus OutboxEventStatus
	Valid             bool // Valid is true if OutboxEventStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOutboxEventStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OutboxEventStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OutboxEventStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOutboxEventStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OutboxEventStatus), nil
}

type InboxEvent struct {
	EventID       pgtype.UUID
	Seq           int64
	Topic         string
	Key           string
	Type          string
	Version       int32
	Producer      string
	Payload       []byte
	Partition     int32
	KafkaOffset   int64
	ReservedBy    pgtype.Text
	Status        InboxEventStatus
	Attempts      int32
	NextAttemptAt pgtype.Timestamptz
	LastAttemptAt pgtype.Timestamptz
	LastError     pgtype.Text
	ProcessedAt   pgtype.Timestamptz
	ProducedAt    pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

type OutboxEvent struct {
	EventID       pgtype.UUID
	Seq           int64
	Topic         string
	Key           string
	Type          string
	Version       int32
	Producer      string
	Payload       []byte
	ReservedBy    pgtype.Text
	Status        OutboxEventStatus
	Attempts      int32
	NextAttemptAt pgtype.Timestamptz
	LastAttemptAt pgtype.Timestamptz
	LastError     pgtype.Text
	SentAt        pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}
